name: Build Assembly

on:
  push:
    branches:
      - main  # ÐÞ¸ÄÎªÄãµÄÄ¬ÈÏ·ÖÖ§

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install GCC
      run: |
        choco install mingw -y
        RefreshEnv

    - name: Assemble and Link
      run: |
        gcc -o CreateUser.exe CreateUser.exe.asm

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-artifact
        path: CreateUser.exe
