name: Build Assembly

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install nasm -y
        sudo apt-get install mingw-w64 -y

    - name: Build Assembly
      run: |
        nasm -f win64 CreateUser.exe.asm -o CreateUser.obj
        x86_64-w64-mingw32-gcc -o CreateUser.exe main.c CreateUser.obj -lnetapi32

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-artifact
        path: CreateUser.exe
