name: Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up MSVC
      uses: microsoft/setup-msbuild@v1

    - name: Install CMake
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Build
      run: |
        mkdir build
        cmake .
       

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-artifact
        path: build\CreateUser.exe
